"""init

Revision ID: d199a3e17af8
Revises: 
Create Date: 2026-07-20 20:30:14.609949
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd199a3e17af8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create schemas for self-contained migration
    for schema in ('ai', 'company', 'core', 'document', 'market', 'portfolio', 'research'):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_workflows',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('workflow_type', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_ai_workflows_id'), 'ai_workflows', ['id'], unique=False, schema='ai')
    op.create_index(op.f('ix_ai_ai_workflows_name'), 'ai_workflows', ['name'], unique=False, schema='ai')
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt_template', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_prompt_templates_id'), 'prompt_templates', ['id'], unique=False, schema='ai')
    op.create_index(op.f('ix_ai_prompt_templates_name'), 'prompt_templates', ['name'], unique=True, schema='ai')
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('headquarters', sa.String(length=256), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_index(op.f('ix_company_companies_id'), 'companies', ['id'], unique=False, schema='company')
    op.create_index(op.f('ix_company_companies_ticker'), 'companies', ['ticker'], unique=True, schema='company')
    op.create_table('event_log',
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_event_log_entity_id'), 'event_log', ['entity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_event_log_event_type'), 'event_log', ['event_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_event_log_id'), 'event_log', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_event_log_occurred_at'), 'event_log', ['occurred_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_event_log_source'), 'event_log', ['source'], unique=False, schema='core')
    op.create_table('financial_metrics',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=16), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_index(op.f('ix_market_financial_metrics_id'), 'financial_metrics', ['id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_financial_metrics_ticker'), 'financial_metrics', ['ticker'], unique=False, schema='market')
    op.create_table('macro_indicators',
    sa.Column('indicator', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_index(op.f('ix_market_macro_indicators_id'), 'macro_indicators', ['id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_macro_indicators_indicator'), 'macro_indicators', ['indicator'], unique=False, schema='market')
    op.create_table('stock_prices',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_index(op.f('ix_market_stock_prices_id'), 'stock_prices', ['id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_stock_prices_ticker'), 'stock_prices', ['ticker'], unique=False, schema='market')
    op.create_table('holdings',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_cost_basis', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_holdings_id'), 'holdings', ['id'], unique=False, schema='portfolio')
    op.create_index(op.f('ix_portfolio_holdings_ticker'), 'holdings', ['ticker'], unique=False, schema='portfolio')
    op.create_table('watchlists',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_watchlists_id'), 'watchlists', ['id'], unique=False, schema='portfolio')
    op.create_table('company_tags',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_index(op.f('ix_company_company_tags_id'), 'company_tags', ['id'], unique=False, schema='company')
    op.create_table('documents',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='document'
    )
    op.create_index(op.f('ix_document_documents_company_id'), 'documents', ['company_id'], unique=False, schema='document')
    op.create_index(op.f('ix_document_documents_doc_type'), 'documents', ['doc_type'], unique=False, schema='document')
    op.create_index(op.f('ix_document_documents_id'), 'documents', ['id'], unique=False, schema='document')
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['portfolio.watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_watchlist_items_id'), 'watchlist_items', ['id'], unique=False, schema='portfolio')
    op.create_index(op.f('ix_portfolio_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False, schema='portfolio')
    op.create_table('research_sessions',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index(op.f('ix_research_research_sessions_company_id'), 'research_sessions', ['company_id'], unique=False, schema='research')
    op.create_index(op.f('ix_research_research_sessions_id'), 'research_sessions', ['id'], unique=False, schema='research')
    op.create_index(op.f('ix_research_research_sessions_status'), 'research_sessions', ['status'], unique=False, schema='research')
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='document'
    )
    op.create_index(op.f('ix_document_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False, schema='document')
    op.create_index(op.f('ix_document_document_chunks_embedding_id'), 'document_chunks', ['embedding_id'], unique=False, schema='document')
    op.create_index(op.f('ix_document_document_chunks_id'), 'document_chunks', ['id'], unique=False, schema='document')
    op.create_table('investment_journal',
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('research_session_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['research_session_id'], ['research.research_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_investment_journal_entry_type'), 'investment_journal', ['entry_type'], unique=False, schema='portfolio')
    op.create_index(op.f('ix_portfolio_investment_journal_id'), 'investment_journal', ['id'], unique=False, schema='portfolio')
    op.create_table('research_evidences',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=256), nullable=True),
    sa.Column('source_title', sa.String(length=512), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research.research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index(op.f('ix_research_research_evidences_id'), 'research_evidences', ['id'], unique=False, schema='research')
    op.create_index(op.f('ix_research_research_evidences_session_id'), 'research_evidences', ['session_id'], unique=False, schema='research')
    op.create_table('research_reports',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research.research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index(op.f('ix_research_research_reports_id'), 'research_reports', ['id'], unique=False, schema='research')
    op.create_index(op.f('ix_research_research_reports_session_id'), 'research_reports', ['session_id'], unique=False, schema='research')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_research_reports_session_id'), table_name='research_reports', schema='research')
    op.drop_index(op.f('ix_research_research_reports_id'), table_name='research_reports', schema='research')
    op.drop_table('research_reports', schema='research')
    op.drop_index(op.f('ix_research_research_evidences_session_id'), table_name='research_evidences', schema='research')
    op.drop_index(op.f('ix_research_research_evidences_id'), table_name='research_evidences', schema='research')
    op.drop_table('research_evidences', schema='research')
    op.drop_index(op.f('ix_portfolio_investment_journal_id'), table_name='investment_journal', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_investment_journal_entry_type'), table_name='investment_journal', schema='portfolio')
    op.drop_table('investment_journal', schema='portfolio')
    op.drop_index(op.f('ix_document_document_chunks_id'), table_name='document_chunks', schema='document')
    op.drop_index(op.f('ix_document_document_chunks_embedding_id'), table_name='document_chunks', schema='document')
    op.drop_index(op.f('ix_document_document_chunks_document_id'), table_name='document_chunks', schema='document')
    op.drop_table('document_chunks', schema='document')
    op.drop_index(op.f('ix_research_research_sessions_status'), table_name='research_sessions', schema='research')
    op.drop_index(op.f('ix_research_research_sessions_id'), table_name='research_sessions', schema='research')
    op.drop_index(op.f('ix_research_research_sessions_company_id'), table_name='research_sessions', schema='research')
    op.drop_table('research_sessions', schema='research')
    op.drop_index(op.f('ix_portfolio_watchlist_items_watchlist_id'), table_name='watchlist_items', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_watchlist_items_id'), table_name='watchlist_items', schema='portfolio')
    op.drop_table('watchlist_items', schema='portfolio')
    op.drop_index(op.f('ix_document_documents_id'), table_name='documents', schema='document')
    op.drop_index(op.f('ix_document_documents_doc_type'), table_name='documents', schema='document')
    op.drop_index(op.f('ix_document_documents_company_id'), table_name='documents', schema='document')
    op.drop_table('documents', schema='document')
    op.drop_index(op.f('ix_company_company_tags_id'), table_name='company_tags', schema='company')
    op.drop_table('company_tags', schema='company')
    op.drop_index(op.f('ix_portfolio_watchlists_id'), table_name='watchlists', schema='portfolio')
    op.drop_table('watchlists', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_holdings_ticker'), table_name='holdings', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_holdings_id'), table_name='holdings', schema='portfolio')
    op.drop_table('holdings', schema='portfolio')
    op.drop_index(op.f('ix_market_stock_prices_ticker'), table_name='stock_prices', schema='market')
    op.drop_index(op.f('ix_market_stock_prices_id'), table_name='stock_prices', schema='market')
    op.drop_table('stock_prices', schema='market')
    op.drop_index(op.f('ix_market_macro_indicators_indicator'), table_name='macro_indicators', schema='market')
    op.drop_index(op.f('ix_market_macro_indicators_id'), table_name='macro_indicators', schema='market')
    op.drop_table('macro_indicators', schema='market')
    op.drop_index(op.f('ix_market_financial_metrics_ticker'), table_name='financial_metrics', schema='market')
    op.drop_index(op.f('ix_market_financial_metrics_id'), table_name='financial_metrics', schema='market')
    op.drop_table('financial_metrics', schema='market')
    op.drop_index(op.f('ix_core_event_log_source'), table_name='event_log', schema='core')
    op.drop_index(op.f('ix_core_event_log_occurred_at'), table_name='event_log', schema='core')
    op.drop_index(op.f('ix_core_event_log_id'), table_name='event_log', schema='core')
    op.drop_index(op.f('ix_core_event_log_event_type'), table_name='event_log', schema='core')
    op.drop_index(op.f('ix_core_event_log_entity_id'), table_name='event_log', schema='core')
    op.drop_table('event_log', schema='core')
    op.drop_index(op.f('ix_company_companies_ticker'), table_name='companies', schema='company')
    op.drop_index(op.f('ix_company_companies_id'), table_name='companies', schema='company')
    op.drop_table('companies', schema='company')
    op.drop_index(op.f('ix_ai_prompt_templates_name'), table_name='prompt_templates', schema='ai')
    op.drop_index(op.f('ix_ai_prompt_templates_id'), table_name='prompt_templates', schema='ai')
    op.drop_table('prompt_templates', schema='ai')
    op.drop_index(op.f('ix_ai_ai_workflows_name'), table_name='ai_workflows', schema='ai')
    op.drop_index(op.f('ix_ai_ai_workflows_id'), table_name='ai_workflows', schema='ai')
    op.drop_table('ai_workflows', schema='ai')
    # ### end Alembic commands ###
